# Generated by Django 6.0.4 on 2026-04-10 06:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='日付')),
                ('title', models.CharField(max_length=100, verbose_name='内容')),
                ('amount', models.PositiveIntegerField(verbose_name='金額')),
                ('category', models.CharField(choices=[('shokuhi', '食費'), ('nichiyou', '日用品'), ('koutsu', '交通費'), ('kounetsu', '光熱費'), ('goraku', '娯楽・趣味'), ('sonota', 'その他')], default='shokuhi', max_length=20, verbose_name='カテゴリ')),
            ],
        ),
    ]
