# Generated by Django 6.0.4 on 2026-04-13 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='balance_type',
            field=models.CharField(choices=[('out', '支出'), ('in', '収入')], default='out', max_length=3, verbose_name='収支タイプ'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('shokuhi', '食費'), ('nichiyou', '日用品'), ('koutsu', '交通費'), ('kounetsu', '光熱費'), ('goraku', '娯楽・趣味'), ('kyuryo', '給料'), ('sonota', 'その他')], default='shokuhi', max_length=20, verbose_name='カテゴリ'),
        ),
    ]
