# Generated by Django 6.0.4 on 2026-04-30 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense_balance_type_alter_expense_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(choices=[('cash', '現金'), ('card', 'クレジットカード'), ('debit', 'デビットカード'), ('qr', 'QR決済'), ('none', 'なし（収入など）')], default='cash', max_length=10, verbose_name='支払い方法'),
        ),
    ]
